sudo: required
language: node_js
node_js:
- stable
services:
- docker
env:
  global:
  - EB_REGION="eu-west-2"
  - secure: $AWS_ACCOUNT_ID
  - secure: $AWS_ACCESS_KEY_ID
  - secure: $AWS_SECRET_ACCESS_KEY
before_install:
- pip install awscli --upgrade --user
- export PATH=$PATH:$HOME/.local/bin
script:
- docker build -t test:latest .
deploy:
  provider: script
  script: docker_push.sh
  on:
    branch: master