sudo: required
language: node_js
node_js:
- stable
services:
- docker
env:
  global:
  - DOCKER_REPO=test
  - EB_REGION="eu-west-2"
  - secure: $AWS_ACCOUNT_ID
  - secure: $AWS_ACCESS_KEY_ID
  - secure: $AWS_SECRET_ACCESS_KEY
before_install:
-  pip install --upgrade pip
-  pip -v
- pip install awscli
- export PATH=$PATH:$HOME/.local/bin
script:
- docker build -t $DOCKER_REPO .
deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master