name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with: BLA:${{secrets.MY_SUPER_SECRET}}
      - name: Decrypt large secret
        run: echo 'BLA=${{secrets.MY_SUPER_SECRET}}' > .env
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}
      - name: Test printing your secret (Remove this step in production)
        run: cat .env

      
