name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Hello world action

        env: # Or as an environment variable
          super_secret:  ${{secrets.MY_SUPER_SECRET}}
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo 'BLA=${{env.MY_SUPER_SECRET}}' > .env
          cat .env
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo 'BLA= ${{secrets.MY_SUPER_SECRET}}' > .env
          cat .env
      - name: Run a multi-line script
        uses: echo ' ${{secrets.MY_SUPER_SECRET}}' > .env
        with: 
          MY_SUPER_SECRET: ${{ secrets.MY_SUPER_SECRET }} 
