name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Hello world action
      with: # Set the secret as an input
        super_secret: ${{ secrets.MY_SUPER_SECRET }}
      env: # Or as an environment variable
        super_secret: ${{ secrets.MY_SUPER_SECRET }}

    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        echo 'BLA=${{secrets.MY_SUPER_SECRET}}' > .env
        cat .env
