name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with: 
          LARGE_SECRET_PASSPHRASE:${{secrets.MY_SUPER_SECRET}}
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.MY_SUPER_SECRET }}
      - name: Test printing your secret (Remove this step in production)
        run: cat .env

      
