name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Hello world action
        with: # Set the secret as an input
          super_secret: ${{ secrets.MY_SUPER_SECRET }}
      - uses: actions/checkout@v1
        with: BLA:${{secrets.MY_SUPER_SECRET}}
      - name: Decrypt large secret
        run: echo 'BLA=${{secrets.MY_SUPER_SECRET}}' > .env
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.MY_SUPER_SECRET }}
      - name: Test printing your secret (Remove this step in production)
        run: cat .env

      
